# App info
name: flutter_defender_game
description: A new Flutter project.
publish_to: 'none'
version: 0.0.0

# Environments
environment:
  sdk: ">=2.17.0 <3.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flame: ^1.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# App Resouces
flutter:
  uses-material-design: true

  assets:
    - assets/images/